### ISSUE TITLE
Table indexing

### ISSUE THREAD

**Issue by Cameron-D** [MyBBStuff/SimpleLikes#12]
As noticed in [this thread](http://community.mybb.com/thread-157813-post-1098091.html#pid1098091) and my own testing, the `post_likes` table lacks an index on the `post_id` column which results in extremely long-running queries on thread view if like counts are shown in the postbit (25 seconds in my case, for a table of 300k likes). Adding an index to the `post_id` column reduced it to 300ms for me - still somewhat long, but over 70x faster.

~~Additionally, the table has an `id` column acting as a primary key but the ID is never referenced (well, looking at the `likePost()` function it isn't, but it may be elsewhere that I didn't notice) so that column could be removed the the primary key made to be `PRIMARY KEY (post_id, user_id)`.
Probably won't be any performance changes but removes some unneeded data from the table and will eliminate any possibility of a user somehow double-liking a post.~~

Just realised that the `id` gets used for ordering so disregard that. A unique constraint on those columns could still be done though.

**Comment by euantorano** [comment]
Sorted in v2.0.0 :smile:
