### ISSUE TITLE
Like Button Does Not Work Sometimes + Flickering Button

### ISSUE THREAD

**Issue by nollidnosnhoj** [MyBBStuff/SimpleLikes#13]
When I click on the like button, the button will keep switching to Like and Unlike, to eventually staying at like. Also the like bar won't appear after I refresh the page. Maybe it would be better if it appears after liking a post. 

Sometimes I would like a post, but refresh a page to find out I didn't....

Here's a video link of my problem: https://www.youtube.com/watch?v=vRO8pbPwgDY

Forum: http://www.tripulse.net/forum/

**Comment by euantorano** [comment]
Sounds like the script is in your headerinclude template multiple times. Can you post that template?

**Comment by nollidnosnhoj** [comment]
{$stylesheets}
{$myprofile_headerinclude}
<link rel="alternate" type="application/rss+xml" title="{$lang->latest_threads} (RSS 2.0)" href="{$mybb->settings['bburl']}/syndication.php" />
<link rel="alternate" type="application/atom+xml" title="{$lang->latest_threads} (Atom 1.0)" href="{$mybb->settings['bburl']}/syndication.php?type=atom1.0" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="icon" type="image/png" href="{$mybb->settings['bburl']}/favicon.png">
<link rel="stylesheet" href="{$mybb->asset_url}/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<link rel="stylesheet" href="{$mybb->asset_url}/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
<link rel="stylesheet" href="{$mybb->asset_url}/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
<meta http-equiv="Content-Type" content="text/html; charset={$charset}" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<script type="text/javascript" src="{$mybb->asset_url}/jscripts/jquery.js?ver=1800"></script>
<script type="text/javascript" src="{$mybb->asset_url}/jscripts/jquery.plugins.min.js?ver=1800"></script>
<script type="text/javascript" src="{$mybb->asset_url}/jscripts/general.js?ver=1800"></script>
<script type="text/javascript" src="{$mybb->asset_url}/jscripts/audentio/dazzle/functions.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script language="javascript" type="text/javascript" src="{$mybb->settings['bburl']}/jscripts/myadvertisements.js"></script>
<script language="javascript" type="text/javascript" src="{$mybb->settings['bburl']}/jscripts/custom_status.js"></script>
<script type="text/javascript" src="{$mybb->asset_url}/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
<script type="text/javascript" src="{$mybb->asset_url}/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
<script type="text/javascript" src="{$mybb->asset_url}/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
<script type="text/javascript" src="{$mybb->asset_url}/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
<script type="text/javascript">
if (typeof jQuery == 'undefined') {
    document.write(unescape("%3Cscript src='http://code.jquery.com/jquery-1.7.2.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>
<script type="text/javascript">

</script>



<script type="text/javascript">
jQuery(function($) {
    $(".clickedbuttons").hide();
    $(".buttons").click(function() {
        $(".sidebar").animate({height: "hide", opacity: 0}, 500,
            function() {
                $(".forums").animate({width: "100%"}, 500);
            });
        $(this).hide();
        $(".clickedbuttons").show();
        $.cookie("sidebar","collapsed", {expires: 365});
        return false;
    });
    $(".clickedbuttons").click(function() {
        $(".forums").animate({width: "75%"}, 500,
            function() {
                $(".sidebar").animate({height: "show", opacity: 1}, 500);
            });
        $(this).hide();
        $(".buttons").show();
        $.cookie("sidebar","expanded", {expires: 365});
        return false;
    });
    if($.cookie("sidebar") == "collapsed") {
        $(".buttons").hide();
        $(".clickedbuttons").show();
        $(".forums").css("width","100%");
        $(".sidebar").hide();
    };
});
</script>



<script type="text/javascript">
$(document).ready(function() {
   $('.post_body img').each(function() {
       var currentImage = $(this);
       
       if (currentImage.parent().is('a') == false)
       {
           currentImage.wrap("<a target='_blank' class='fancybox' href='" + currentImage.attr("src") + "'</a>");
       }

   });

   $(".fancybox").fancybox();
});
</script>



{$myalerts_js}



<script type="text/javascript">
    var unreadAlerts = {$mybb->user['unreadAlerts']};
</script><script type="text/javascript" src="{$mybb->asset_url}/jscripts/like_system.min.js"></script>

**Comment by euantorano** [comment]
Is that definitely the full template? Your site does have the JS there twice (actually three times, but one is a broken link...), but that template only includes it once. See the below screenshot:

![screen shot 2015-07-26 at 13 24 23](https://cloud.githubusercontent.com/assets/748913/8893860/b26d5d92-3399-11e5-8227-97c8cfd17a11.png)

**Comment by nollidnosnhoj** [comment]
Okay.... I changed my headerinclude to make sure there's only one like system script in the headerinclude.
http://pastebin.com/xxxSRmmj

I noticed that the script appeared in every Global template. Same as the myalerts. Is this normal?

**Comment by euantorano** [comment]
Yes, it's a bug in MyBB 1.8 that is fixed in the next release of MyBB. You'll have to remove the other template edits. The release thread lists which templates should be changed.

**Comment by nollidnosnhoj** [comment]
Where can I find the release thread?

**Comment by nollidnosnhoj** [comment]
Well, hopefully this gets fixed soon. I would hate having to update the plugin, only to remove those scripts again from the global templates.
