### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dusty459** [MyBBStuff/SimpleLikes#15]
Fatal error: Class 'MybbStuff_SimpleLikes_Import_Manager' not found in /home4/*****/public_html/admin/modules/mybbstuff_likes/import.php on line 22

**Comment by euantorano** [comment]
Can you make sure the file `inc/plugins/MybbStuff/SimpleLikes/src/Import/Manager.php` exists?

**Comment by dusty459** [comment]
hi yes I can see it there

**Comment by euantorano** [comment]
What version of PHP are you using? The class should be getting autoloader, but doesn't seem to be in your case.

**Comment by dusty459** [comment]
its using 5.4.45

**Comment by dusty459** [comment]
can I just say thank you very much for your fast response

**Comment by euantorano** [comment]
Can you try the change from this commit: b3c9db

And no problem, you caught me at just the right time :wink:

**Comment by dusty459** [comment]
could you say again what do you need me to do

**Comment by euantorano** [comment]
Replace the file `admin/modules/mybbstuff_likes/import.php` with the content found here: https://raw.githubusercontent.com/MyBBStuff/SimpleLikes/b3c9dbbc8e5aabe5863a73793e528adaf2550e51/admin/modules/mybbstuff_likes/import.php

**Comment by dusty459** [comment]
right I get This plugin requires PluginLibrary, please ensure it is installed correctly.  when I click to activate when on plugins in the admin cp

**Comment by dusty459** [comment]
so that fixed that error but now when I go to activate it just says This plugin requires PluginLibrary, please ensure it is installed correctly.  I dragged and dropped the files into my public html

**Comment by euantorano** [comment]
Yep, you'll need to get PluginLibrary then: https://github.com/frostschutz/MyBB-PluginLibrary

**Comment by dusty459** [comment]
thank you very much
