### ISSUE TITLE
Change appearance of liked line

### ISSUE THREAD

**Issue by metulburr** [MyBBStuff/SimpleLikes#17]
How can you change the CSS of the line that shows 
"X likes this post" 

Its by default black, i would like to make the background transparent so that its not so vibrant and show the default layout of white.

**Comment by euantorano** [comment]
Hi,

By default it uses the `.tcat` class, but also adds a `.likebar` class, so you can style it as follows:

```
.tcat.likebar {
    background: blue; // Or whatever colour you want...
}
```
