### ISSUE TITLE
only admins and mods can use this

### ISSUE THREAD

**Issue by metulburr** [MyBBStuff/SimpleLikes#18]
One of my users informed me they do not get this option in their postbit. AFter checking a bogus account, i see that only admins and mods can see and use the like post button. There is no option for certain user groups in the settings...there are only 5 setttings.

**Comment by euantorano** [comment]
Hi,

Have a look at the user group permissions in ACP > Users and Groups > Usergroups.

**Comment by metulburr** [comment]
oh i didnt realize it created a new category for it...thanks
