### ISSUE TITLE
modify the image to something different

### ISSUE THREAD

**Issue by metulburr** [MyBBStuff/SimpleLikes#19]
I actually do want the thumbs up image. However i am changing the buttons_sprite.png to use other images. Every time i do this the simple likes image changes too. But i dont want it to. I would like to change simple likes plugin to stay with the thumbs up image.

I dont see an option in the settings for which image to use...and i dont see in the code anywhere it links to
images/buttons_sprite.png to use the image.

**Comment by euantorano** [comment]
Hi,

The buttons use CSS classes, with the sprite. If you look at the `simplelikes.css` stylesheet in ACP > Templates & Style > *YOUR THEME* > simplelikes.css you will see a stylesheet like this: https://github.com/MyBBStuff/SimpleLikes/blob/master/inc/plugins/MybbStuff/SimpleLikes/stylesheets/simplelikes.css#L1

All you need to do is change the background position for the button to match your updated sprite.

**Comment by metulburr** [comment]
oh ok i didnt know thats how it it switched between the sprites. thanks.
