### ISSUE TITLE
ACP Plugins Page Blank

### ISSUE THREAD

**Issue by AfikHabaz** [MyBBStuff/SimpleLikes#21]
After uploading the files to my host
i went to the plugins page to activate the plugin
and it was blank.

**Comment by euantorano** [comment]
Can you check your servers error log to see if any errors are logged?

**Comment by chack1172** [comment]
I can't replicate this issue

**Comment by euantorano** [comment]
Yeah, this is likely due to a missing file like the autoloader. Closing.
