### ISSUE TITLE
clicking on alerts does not clear them

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#32]
if you click on an alert from the simple likes plugin, it does not clear it and/or mark it as read.  so if you have 3 alerts from liked posts, click on all of them, it'll still show that you have 3 alerts.

**Comment by andrewjs18** [comment]
seems to work for everything except simple likes - PMs, replies, etc..

**Comment by chack1172** [comment]
I found out that the link used is the post url and not the myalerts url that set the alert read. I'll push a pull later.

**Comment by andrewjs18** [comment]
the above PR seems to take care of this issue.  thanks, @chack1172!
