### ISSUE TITLE
removing a like should remove the alert

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#33]
not doing so leads to confusion as the alert is no longer valid.  the thank you/like plugin does this.

**Comment by chack1172** [comment]
Isn't it already deleting alerts when unlike?
https://github.com/MyBBStuff/SimpleLikes/blob/master/inc/plugins/simplelikes.php#L875

**Comment by chack1172** [comment]
Ok. I found what are the problems. First in the query that I sent in the past comment we should use `from_user_id` and not `uid`. The second problem is that the function deleteAlerts of MyAlerts tries to delete the alerts he received but it checks if the alerts belongs to who unliked the message. So we can't use that method.

**Comment by chack1172** [comment]
I sent a new commit to fix it. I didn't test the second commit yesterday, sorry.

**Comment by andrewjs18** [comment]
fixed now.  if someone removes a like, refresh the page and the like is removed from the alerts window.
