### ISSUE TITLE
add the like button in tapatalk

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#34]
this is an enhancement that the thank you/like plugin had.  since a lot of people like tapatalk, they like this feature.

**Comment by euantorano** [comment]
I’ve never used tapatalk, so I’d need to look at how that system works.

**Comment by andrewjs18** [comment]
perhaps we can ask Eldenroot as he has it integrated in his plugin.

**Comment by Eldenroot** [comment]
Hi guys. Tapatalk support was added by an original plugin author G33K. I just overtook abandoned plugin and maintain it. So I am not sure how to add it.

However I dont recommend to add it, it is quite buggy and Tapatalk is getting less popular. Also there is no detailed documentation. Anyway it is up to you, try to check the code used in Thank you/like plugin, maybe it could help.

**Comment by euantorano** [comment]
I'll have a look, thanks @Eldenroot!

**Comment by andrewjs18** [comment]
thanks for the feedback, @Eldenroot

**Comment by chack1172** [comment]
So, after some search I found out that the tapatalk integration is not done in the thank you/like plugin system. The tapatalk mybb plugin has been developed integrating that plugin so the only way to make this plugin work in tapatalk is to edit tapatalk plugin.

**Comment by andrewjs18** [comment]
interesting.  but how does it reapply those edits when tapatalk is updated?

**Comment by andrewjs18** [comment]
@euantorano @chack1172, if I reach out to tapatalk about adding support for this plugin, what's the best way we can integrate the 2?

**Comment by chack1172** [comment]
I don't know at the moment. I'm checking tapatalk files to understand how they do it with thank you/like plugin.

**Comment by andrewjs18** [comment]
perhaps something can be implemented like the google seo plugin uses where after a forum update is performed, you have the ability to reapply the core edits via a button on the plugins page.  of course rather than a core forum update, it'd apply to tapatalk updates..

**Comment by andrewjs18** [comment]
perfect.  nice work with the PR, @chack1172.
