### ISSUE TITLE
added more usable variables for language file

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#35]
I'm not sure if there's more available to use, but I'd like to change up the text that a user sees when someone likes one of their posts.  What I'd really like to do is change 'your post' to the actual name of the post so the alert is more useful.

see below as an example of the current text format:

![142 03 32](https://user-images.githubusercontent.com/2748980/43823036-d7577f48-9abb-11e8-8972-e946363498f6.jpg)

**Comment by euantorano** [comment]
The language variable is defined here: https://github.com/MyBBStuff/SimpleLikes/blob/master/inc/languages/english/simplelikes.lang.php#L6

The post/thread subject would need to be stored with the like, or queried (slower, could ad dup to a bunch of queries) before formatting: https://github.com/MyBBStuff/SimpleLikes/blob/master/inc/plugins/MybbStuff/SimpleLikes/src/LikeFormatter.php#L38

**Comment by andrewjs18** [comment]
yep, I set up a patch in patches to adjust the wording in the alert, but for some reason it shifts the text from left aligned to center aligned - photos will be below.

I think it's worth adding the queries to make the alert more useful, personally.  perhaps it can set some sort of limit to reduce the amount of queries..

before applying patch:
![145 01 22](https://user-images.githubusercontent.com/2748980/43879572-bf0246a0-9b72-11e8-9c62-1bcf93b776e8.jpg)

after patch:
![146 01 23](https://user-images.githubusercontent.com/2748980/43879619-e736e734-9b72-11e8-8043-39531e934172.jpg)

**Comment by chack1172** [comment]
@euantorano I think the best way is to store the post subject like you did for quoted messages.

**Comment by andrewjs18** [comment]
the above PR makes the alert more useful now by including the thread title.  thanks!
