### ISSUE TITLE
deactivating & uninstalling does not remove 'like system' tab

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#39]
after deactivating and uninstalling simple likes on my test board, it did not remove the 'like system' tab in the admin cp:

![147 03 29](https://user-images.githubusercontent.com/2748980/43999719-14b51644-9de0-11e8-97a0-119a3db158ec.jpg)

![148 03 29](https://user-images.githubusercontent.com/2748980/43999722-17a1faf2-9de0-11e8-8b54-8c5ac4794ce1.jpg)

**Comment by euantorano** [comment]
I believe that’s because the tab is added by the module, rather than the plugin. Does it disappear if you delete the module from admin/modules?

**Comment by WildcardSearch** [comment]
@euantorano the issue is that in `admin/mybbstuff_likes/module_meta.php` in `mybbstuff_likes_action_handler()`, there should be a check to see if the plugin is activated, and if not, return `false`.

**Comment by chack1172** [comment]
I sent a PR to fix this

**Comment by andrewjs18** [comment]
the above PR takes care of this.  thanks, @chack1172
