### ISSUE TITLE
Conversion instructions for G33K's like/thank you system

### ISSUE THREAD

**Issue by Ar7ific1al** [MyBBStuff/SimpleLikes#5]
There is a striking lack of instruction on how to convert from g33k's system to SimpleLikes. There's nothing in either plugin's settings, and there is zero instruction anywhere that I can find. Perhaps this should be mentioned somewhere, perhaps in the readme.md.

**Comment by euantorano** [comment]
This should be clearer in 2.0.0 with the addition of an ACP module to manage conversions.
